# Generated by Django 3.1.7 on 2021-03-31 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id_unit', models.AutoField(primary_key=True, serialize=False)),
                ('fakultas', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_dekan', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_karyawan', models.CharField(max_length=200)),
                ('telp_karyawan', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('pimpinan', 'pimpinan'), ('karyawan', 'karyawan')], max_length=150, null=True)),
                ('id_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akses.unit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
