# Generated by Django 3.1.3 on 2021-06-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyawan',
            options={'verbose_name_plural': 'Karyawan'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': 'Unit'},
        ),
    ]
