# Generated by Django 3.1.3 on 2021-06-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('akses', '0002_auto_20210613_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
