# Generated by Django 3.1.3 on 2021-06-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('akses', '0003_unit_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
