# Generated by Django 3.1.3 on 2021-06-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akses', '0004_auto_20210613_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='group',
        ),
    ]
